### ISSUE TITLE
检查服务器:域名解析错误

### ISSUE THREAD

**Issue by luxuryhuster** [Bambi5/Collei_Launcher#1]
你好！当gamehost是公网ip而不是域名时返回:域名解析错误
原因是Dns.GetHostEntry()可以解析域名和局域网ip，不能解析公网ip
/Bambi5_Launcher/Check_Form.cs 第133行
![issue0911](https://user-images.githubusercontent.com/50796334/189510958-0fc93f9d-eb10-4ab9-aed5-8c76cb9a74ce.png)

**Comment by Bambi5** [comment]
感谢反馈！已改为GetHostAddresses，将随1.2.4版本修复
